org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
neo_version_range=[21.1.235,)
loader_version_range=[4,)

mod_id=farmingexperiencecore
mod_name=Farming Experience Core
mod_license=MIT
mod_version=26.08.05-1.21-neoforge
mod_group_id=com.axperty.farmingexperiencecore
mod_authors=Axperty
mod_description=Core mod for the Farming Experience modpack.